name: example
description: Sample app for sidekick animations

version: 1.0.0+1

environment:
  sdk: ">=2.13.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

  flutter_sidekick:
    path: ../

publish_to: none

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
